name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check formatting
      run: |
        rustup component add rustfmt --toolchain nightly
        cargo +nightly fmt --all --check

    - name: Run clippy (no default features)
      run: |
        cargo clippy --all-targets --no-default-features -- -D warnings

    - name: Run tests (debug mode, no default features)
      run: |
        rustup show active-toolchain
        cargo test --no-default-features

    - name: Run tests (release mode, no default features)
      run: |
        rustup show active-toolchain
        cargo test --release --no-default-features

    - name: Install dependencies
      run: |
        sudo apt-get remove -y man-db || true # to speed up
        sudo apt-get update
        sudo apt-get install libhdf5-dev --no-install-recommends

    - name: Run clippy
      run: |
        cargo clippy --all-targets -- -D warnings

    - name: Run tests (debug mode)
      run: |
        rustup show active-toolchain
        cargo test

    - name: Run tests (release mode)
      run: |
        rustup show active-toolchain
        cargo test --release

    - name: Check Docs
      run: RUSTDOCFLAGS="-D warnings -D missing_docs" cargo doc --no-deps --document-private-items
